# Generated by Django 4.2.7 on 2024-06-23 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0002_student_delete_stu'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Stu',
        ),
    ]
